### ISSUE TITLE
bt指令无法使用

### ISSUE THREAD

**Issue by zhixia-shijian** [xwy231321/ql-plugin#1]
![1174fc8e64bc67318675a6fd5dca9d2](https://github.com/xwy231321/ql-plugin/assets/140401485/61d565d3-cf59-44e6-9eef-d82881b78fde)

**Comment by xwy231321** [comment]
或者试试能不能打开这个链接http://www.eclzz.fyi/
打不开就是网络问题，运营商拦截了，可以尝试魔法绕过

**Comment by zhixia-shijian** [comment]
> 或者试试能不能打开这个链接http://www.eclzz.fyi/打不开就是网络问题，运营商拦截了，可以尝试魔法绕过

http://www.ciligogo.blog/这个可以在国内打开，希望可以改一下

**Comment by xwy231321** [comment]
> > 或者试试能不能打开这个链接 [http://www.eclzz.fyi/ 打不开就是网络问题，运营商拦截了，可以尝试魔法绕过](http://www.eclzz.fyi/%E6%89%93%E4%B8%8D%E5%BC%80%E5%B0%B1%E6%98%AF%E7%BD%91%E7%BB%9C%E9%97%AE%E9%A2%98%EF%BC%8C%E8%BF%90%E8%90%A5%E5%95%86%E6%8B%A6%E6%88%AA%E4%BA%86%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%B0%9D%E8%AF%95%E9%AD%94%E6%B3%95%E7%BB%95%E8%BF%87)
> 
> [http://www.ciligogo.blog/ 这个可以在国内打开，希望可以改一下](http://www.ciligogo.blog/%E8%BF%99%E4%B8%AA%E5%8F%AF%E4%BB%A5%E5%9C%A8%E5%9B%BD%E5%86%85%E6%89%93%E5%BC%80%EF%BC%8C%E5%B8%8C%E6%9C%9B%E5%8F%AF%E4%BB%A5%E6%94%B9%E4%B8%80%E4%B8%8B)
格式不太一样，不好更换
