### ISSUE TITLE
这只是个建议

### ISSUE THREAD

**Issue by bcuiwikb** [xwy231321/ql-plugin#4]
我发现了一个免费的p站API 可是r18🤔 不知道以后能不能加一个

api 

https://se.csnmb.com/API/P站/tu.php
没有什么特殊的 如果打扰到了 对不起

**Comment by xwy231321** [comment]
很好的API，等有空了我加上，感谢分享🙏

**Comment by xwy231321** [comment]
OK了，也是加上了，希望API撑得住吧
